In [1]:
366*24*60*60

31622400

In [2]:
_/1e6

31.6224

In [1]:
366*24*60*60

31622400

In [2]:
_/1e6

31.6224

this is the amount of seconds in a year


# this is heading one

## this is heading two

* one fish
* two fish
* three fish

**example text**
*emample text*

http://google.com


In [1]:
import numpy as np

an_array=np.array([3,33,333])

print(type(an_array))

<class 'numpy.ndarray'>


In [2]:
print(an_array.shape)

(3,)


In [3]:
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [3]:
import numpy as np

another=np.array([[11,12,13],[21,22,23]])
print(another,another.shape)

[[11 12 13]
 [21 22 23]] (2, 3)


In [13]:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
print(another[1,0], another[1,2])

21 23


In [15]:
a=np.full((3,3), 9)
print(a)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [18]:
a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
a=np.array(np.random.random((3,3)))
print(a)

[[0.83935931 0.37395267 0.82168847]
 [0.14326022 0.91291041 0.86775755]
 [0.63398874 0.74705531 0.48342605]]


In [43]:
b=((a[1: , 1:]))
print(b)

[[0.91291041 0.86775755]
 [0.74705531 0.48342605]]


In [34]:
print('before', a[1,1])
b[0,0]=55
print('after' , a[1,1])

before 55.0
after 55.0


In [45]:
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [53]:
r1=an_array[1:2,:]
print(r1, r1.shape)

[[21 22 23 24]] (1, 4)


In [4]:
an_array=np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print(an_array)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [21]:
row=np.array([0,1,2,0])
col=np.arange(4)
print(row,col)

[0 1 2 0] [0 1 2 3]


In [28]:
for r, c in zip(row,col):
    print(r,", ", c)

0 ,  0
1 ,  1
2 ,  2
0 ,  3


In [33]:
an_array[col,row]+=1000
print(an_array)

[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


In [36]:
an=np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print(an)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [37]:
filter=(an >15)
filter

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [38]:
print(an[filter])

[21 22 23 31 32 33 41 42 43]
